# Generated by Django 5.0.4 on 2024-04-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theads', models.CharField(max_length=200)),
                ('specialties', models.CharField(max_length=200)),
                ('studying_forms', models.CharField(max_length=200)),
                ('places', models.CharField(max_length=200)),
                ('marks', models.CharField(max_length=200)),
                ('prices', models.CharField(max_length=200)),
            ],
        ),
    ]
