# Generated by Django 5.0.4 on 2024-04-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theads', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialties', models.CharField(max_length=200)),
                ('studying_forms', models.CharField(max_length=200)),
                ('places', models.CharField(max_length=200)),
                ('marks', models.CharField(max_length=200)),
                ('prices', models.CharField(max_length=200)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapp.faculty')),
            ],
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
