# Generated by Django 5.0.4 on 2024-04-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_faculty_specialties_delete_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialties',
            name='budget_marks',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='specialties',
            name='payment_marks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
