# Generated by Django 5.0.4 on 2024-05-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_specialties_budget_marks_specialties_payment_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='interests',
            field=models.CharField(default='', max_length=200),
        ),
    ]
